# Build and test the image for a TYPO3 version
# and deploy it if the tests passed
build_test: &build_test
  stage: build_test
  name: "Build image, test under Linux and deploy to Docker Hub"
  os: linux
  dist: bionic
  language: shell
  services:
    - docker    
  addons:
    apt:
      packages:
        - bindfs
  script:
    - .travis/build.sh
    - .travis/linux-tests.sh
  before_deploy:
    - docker login --username "$REGISTRY_USER" --password "$REGISTRY_PASS"
  deploy:
    - provider: script
      script:
        - .travis/push.sh
      skip_cleanup: true
      on:
        all_branches: true


# Test the t3 script with a Docker mockup under macOS
# and deploy the image if the tests passed
# test_macos: &test_macos
#   stage: test_macos
#   name: "Test macOS"
#     os: osx
#     osx_image: xcode11  # required for an up-to-date Homebrew
#     language: shell
#   script:
#     - .travis/macos-tests.sh
#   deploy:
#     - provider: script
#       script:
#         - echo '*** Nothing to do ***'
#       skip_cleanup: true
#       on:
#         all_branches: true


jobs:
  include:
    # Build and test images for various TYPO3 versions
    # and deploy each one if the tests passed
    # - <<: *build_test
    #   env: MAJOR_VER=8

    # - <<: *build_test
    #   env: MAJOR_VER=9

    - <<: *build_test
      env: MAJOR_VER=10 MOST_RECENT=true


    # TODO Test scripts under macOS using the saved test sequence and a Docker mockup
    # - <<: *test_macos
    #   env: MAJOR_VER=10 MOST_RECENT=true
