name: Build, test and deploy typo3-in-a-box container images
on:
  push:
    branches:
      - github-workflow

jobs:
  build:
    name: Build image
    runs-on: ubuntu-18.04
    env:
      MAJOR_VER: 10
      IMAGE: $GITHUB_WORKSPACE/image-$MAJOR_VER
    #   MOST_RECENT: true
      
    steps:
      - name: Checkout $GITHUB_REPOSITORY
        uses: actions/checkout@v2
      - name: Build TYPO3 v$MAJOR_VER image
        run:  $GITHUB_WORKSPACE/.github/workflows/build.sh
      - name: Save TYPO3 v$MAJOR_VER image
        uses: actions/upload-artifact@v1
        with:
          name: image-$MAJOR_VER
          path: $IMAGE

  test:
    name: Test image
    runs-on: ubuntu-18.04
    env:
      T3_ENGINE: podman
      MAJOR_VER: 10
    #   MOST_RECENT: true
      IMAGE: $GITHUB_WORKSPACE/image-$MAJOR_VER
      
    steps:
      - name: Checkout $GITHUB_REPOSITORY
        uses: actions/checkout@v2
      - name: Load TYPO3 v$MAJOR_VER image
        uses: actions/download-artifact@v1
        with:
          name: image-$MAJOR_VER
      - name: Test TYPO3 v$MAJOR_VER image under Linux
        run:  $GITHUB_WORKSPACE/.github/workflows/linux-tests.sh

  deploy:
    name: Deploy image
    runs-on: ubuntu-18.04
    env:
      MAJOR_VER: 10
    #   MOST_RECENT: true
      IMAGE: $GITHUB_WORKSPACE/image-$MAJOR_VER
      
    steps:
      - name: Load TYPO3 v$MAJOR_VER image
        uses: actions/download-artifact@v1
        with:
          name: image-$MAJOR_VER
      - name: Deploy TYPO3 v$MAJOR_VER image to Docker Hub
        env:
          REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
        run:  $GITHUB_WORKSPACE/.github/workflows/push.sh
